// Centralized mock data for food items

const foodData = [
    { 
        img: 'assets/pizza2.png', 
        title: 'Home made pizza', 
        price: '₹190', 
        badge: '50%', 
        rating: '4.7', 
        time: '50-70 min', 
        desc: 'Enjoy authentic home made pizza with fresh ingredients and a crispy base. Delivered hot and fresh to your doorstep.' },
    { 
        img: 'assets/slice.png', 
        title: 'Home made pizza', 
        price: '₹123', 
        badge: '30%', 
        rating: '4.7', 
        time: '50-70 min', 
        desc: 'Classic home made pizza slice, perfect for a quick bite or sharing with friends.'},
    { 
        img: 'assets/cut.png', 
        title: 'Home made pizza', 
        price: '₹190', 
        badge: '20%', 
        rating: '4.7', 
        time: '50-70 min', 
        desc: 'Sliced home made pizza with a variety of toppings to choose from.' },
    { 
        img: 'assets/pizza3.png', 
        title: 'Home made pizza', 
        price: '₹190', 
        badge: '', 
        rating: '4.7', 
        time: '50-70 min', 
        desc: 'A delicious home made pizza, baked to perfection and served hot.' },
    { 
        img: 'assets/pizza1.png', 
        title: 'Home made pizza', 
        price: '₹19', 
        badge: '50%', 
        rating: '4.7', 
        time: '50-70 min', 
        desc: 'Enjoy authentic home made pizza with fresh ingredients and a crispy base. Delivered hot and fresh to your doorstep.' },
    { 
        img: 'assets/pizza4.png', 
        title: 'Home made pizza', 
        price: '₹190', 
        badge: '', 
        rating: '4.7', 
        time: '50-70 min', 
        desc: 'Classic home made pizza slice, perfect for a quick bite or sharing with friends.' },
    { 
        img: 'assets/pizza5.png', 
        title: 'Home made pizza', 
        price: '₹190', 
        badge: '20%', 
        rating: '4.7', 
        time: '50-70 min', 
        desc: 'Sliced home made pizza with a variety of toppings to choose from.' },
    { 
        img: 'assets/pizza6.png', 
        title: 'Home made pizza', 
        price: '₹190', 
        badge: '50%', 
        rating: '4.7', 
        time: '50-70 min', 
        desc: 'A delicious home made pizza, baked to perfection and served hot.' },
    { 
        img: 'assets/pizza2.png', 
        title: 'Home made pizza', 
        price: '₹19', 
        badge: '50%', 
        rating: '4.7', 
        time: '50-70 min', 
        desc: 'Enjoy authentic home made pizza with fresh ingredients and a crispy base. Delivered hot and fresh to your doorstep.' },
    { 
        img: 'assets/slice.png', 
        title: 'Home made pizza', 
        price: '₹190', 
        badge: '', 
        rating: '4.7', 
        time: '50-70 min' , 
        desc: 'Classic home made pizza slice, perfect for a quick bite or sharing with friends.' },
    { 
        img: 'assets/cut.png', 
        title: 'Home made pizza', 
        price: '₹190', 
        badge: '20%', 
        rating: '4.7', 
        time: '50-70 min' ,
        desc: 'Sliced home made pizza with a variety of toppings to choose from.' },
    { 
        img: 'assets/pizza3.png', 
        title: 'Home made pizza', 
        price: '₹190', 
        badge: '', 
        rating: '4.7', 
        time: '50-70 min' ,
        desc: 'A delicious home made pizza, baked to perfection and served hot.' },
    
];